---
- name: Get facts on current container
  community.docker.current_container_facts:

- name: Ensure group 'vector' exists
  become: true
  ansible.builtin.group:
    name: vector

- name: Add the user 'vector'
  become: true
  ansible.builtin.user:
    name: vector
    group: vector

- name: Create the app directory for Vector
  become: true
  ansible.builtin.file:
    path: /opt/vector
    state: directory
    owner: vector
    group: vector

- name: Create the data directory for Vector
  become: true
  ansible.builtin.file:
    path: /var/lib/vector
    state: directory
    owner: vector
    group: vector

- name: Create the config directory for Vector
  become: true
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    owner: vector
    group: vector

- name: Download Vector archive
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version_major }}/vector-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
    dest: "/opt/vector-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
    owner: vector
    group: vector

- name: Extract vector
  become: true
  ansible.builtin.unarchive:
    src: "/opt/vector-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
    dest: /opt/vector
    remote_src: true
    extra_opts: [--strip-components=2]
    owner: vector
    group: vector

- name: Template a file to /etc/vector/vector.toml
  become: true
  ansible.builtin.template:
    src: ./templates/vector.toml
    dest: /etc/vector/vector.toml
    owner: root
    group: vector
    mode: '0644'
  notify: Start vector service

- name: Copy vector executable file to /usr/bin
  become: true
  ansible.builtin.copy:
    src: /opt/vector/bin/vector
    dest: /usr/bin
    remote_src: true
    mode: preserve

- name: Copy systemd service
  become: true
  ansible.builtin.copy:
    src: /opt/vector/etc/systemd/vector.service
    dest: /etc/systemd/system
    remote_src: true
    mode: preserve
